# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FluidInterfaces' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Elephant-Parade', :git => 'https://github.com/HelloElephant/Parade.git', :tag => '1.0.0'
end
